#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
cd "$SCRIPT_DIR"

if [ -f server.env ]; then
  # server.env is generated by install.sh and is intended for local values.
  # shellcheck disable=SC1091
  . ./server.env
fi
if [ -f network.env ]; then
  # shellcheck disable=SC1091
  . ./network.env
fi

SERVER_DIR="${SERVER_DIR:-$SCRIPT_DIR}"
MC_MEMORY="${MC_MEMORY:-1G}"
JAVA_BIN="${JAVA_BIN:-java}"
JAVA_FLAGS="${JAVA_FLAGS:--XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200}"
BIND_IP="${BIND_IP:-}"
ADVERTISE_IP="${ADVERTISE_IP:-}"
JAVA_PORT="${JAVA_PORT:-25565}"
BEDROCK_PORT="${BEDROCK_PORT:-19132}"
FIFO="$SERVER_DIR/.minecraft-console"
PID_FILE="$SERVER_DIR/server.pid"

[ -f paper.jar ] || {
  echo "paper.jar is missing. Run ./install.sh first."
  exit 1
}

# Keep the actual server binding configurable without forcing Android's
# changing Wi-Fi address into the configuration.
if [ -f server.properties ]; then
  if grep -q '^server-ip=' server.properties; then
    sed -i -E "s/^server-ip=.*/server-ip=$BIND_IP/" server.properties
  else
    printf '%s\n' "server-ip=$BIND_IP" >> server.properties
  fi
  sed -i -E "s/^server-port=.*/server-port=$JAVA_PORT/" server.properties
fi

if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "The server is already running (PID $(cat "$PID_FILE"))."
  exit 0
fi

rm -f "$FIFO"
mkfifo "$FIFO"
cleanup() {
  rm -f "$FIFO" "$PID_FILE"
}
trap cleanup EXIT INT TERM

echo "Starting Paper with $MC_MEMORY RAM..."
if [ -n "$ADVERTISE_IP" ]; then
  echo "Java players: $ADVERTISE_IP:$JAVA_PORT"
  echo "Bedrock players: $ADVERTISE_IP:$BEDROCK_PORT"
fi
# The FIFO lets this script safely reload Geyser after its first config file is
# generated, without requiring screen/tmux.
"$JAVA_BIN" $JAVA_FLAGS -Xms"$MC_MEMORY" -Xmx"$MC_MEMORY" -jar paper.jar --nogui \
  < "$FIFO" 2>&1 | tee -a server.log &
server_pid=$!
echo "$server_pid" > "$PID_FILE"

# Open the write end after Java has opened the read end.
exec 3>"$FIFO"

geyser_config="$SERVER_DIR/plugins/Geyser-Spigot/config.yml"
for _ in $(seq 1 90); do
  [ -f "$geyser_config" ] && break
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "Paper stopped during startup. Check server.log."
    exit 1
  fi
  sleep 1
done

if [ -f "$geyser_config" ]; then
  # Geyser's default Bedrock port is 19132. This also makes the auth mode
  # explicit so Bedrock players can join through Floodgate.
  sed -i -E 's/^  auth-type: .*/  auth-type: floodgate/' "$geyser_config" || true
  printf '%s\n' "geyser reload" >&3
  echo "Cross-play ready: Java TCP 25565, Bedrock UDP 19132."
else
  echo "Geyser config was not created yet; check server.log and restart once."
fi

wait "$server_pid"